version: '3'

services:
  react-app:
    container_name: react-app-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production